server1: server1.o
	gcc -g -o server1 server1.c

client1: client1.o
	gcc -g -o client1 client1.c


server2: server2.o
	gcc -g -o server2 server2.c

client2: client2.o
	gcc -g -o client2 client2.c


server3: server3.o
	gcc -g -o server3 server3.c

client3: client3.o
	gcc -g -o client3 client3.c

clean:
	rm -rf *.o client1 client2 client3 server1 server2 server3
